NGINX_GROUP: nginx

NGINX_USER: nginx

INSTALL_PATH: /usr/local/nginx

SBIN_PATH: /usr/sbin/nginx

CONF_PATH: '{{INSTALL_PATH}}/conf/nginx.conf'

PID_PATH: /var/run/nginx.pid

LOCK_PATH: /var/run/nginx.lock

ERROR_LOG_PATH: '{{INSTALL_PATH}}/logs/error.log'

ACCESS_LOG_PATH: '{{INSTALL_PATH}}/logs/access.log'

COMPILE_BASIC_OPTIONS: '--group={{NGINX_GROUP}} --user={{NGINX_USER}} --prefix={{INSTALL_PATH}} --sbin-path={{SBIN_PATH}} --conf-path={{CONF_PATH}} --pid-path={{PID_PATH}} --lock-path={{LOCK_PATH}} --error-log-path={{ERROR_LOG_PATH}} --http-log-path={{ACCESS_LOG_PATH}}'

COMPILE_MODULE_OPTIONS: '--with-http_gzip_static_module --with-http_stub_status_module --with-http_ssl_module --with-pcre --with-file-aio --with-http_realip_module'

COMPILE_OPTIONS: '{{COMPILE_BASIC_OPTIONS}} {{COMPILE_MODULE_OPTIONS}}'

NGINX_VERSION: 1.15.7

